flowchart TD
  subgraph ch1["Chapter 1: 活下去"]
    ch1_01["ch1_01\nnarration"]
    ch1_02["ch1_02\ndialogue"]
    ch1_03["ch1_03\nnarration"]
    ch1_04["ch1_04\nnarration"]
    ch1_05["ch1_05\nnarration"]
    ch1_06["ch1_06\nchoice"]
    ch1_06a["ch1_06a\nnarration"]
    ch1_07["ch1_07\nnarration"]
    ch1_08["ch1_08\ndialogue"]
    ch1_09["ch1_09\ndialogue"]
    ch1_10["ch1_10\nnarration"]
    ch1_11["ch1_11\ndialogue"]
    ch1_12["ch1_12\ndialogue"]
    ch1_13["ch1_13\ngacha_trigger"]
    ch1_14["ch1_14\nphone_notify"]
    ch1_15["ch1_15\nnarration"]
    ch1_16["ch1_16\nnarration"]
    ch1_17["ch1_17\nface_slap"]
    ch1_18["ch1_18\nnarration"]
    ch1_19["ch1_19\ndialogue"]
    ch1_20["ch1_20\nchoice"]
    ch1_20a["ch1_20a\ndialogue"]
    ch1_20b["ch1_20b\ndialogue"]
    ch1_20c["ch1_20c\ndialogue"]
    ch1_21["ch1_21\nnarration"]
    ch1_22["ch1_22\nnarration"]
    ch1_23["ch1_23\ndialogue"]
    ch1_24["ch1_24\nnarration"]
    ch1_25["ch1_25\nnarration"]
  end
  ch1_01 --> ch1_02
  ch1_02 --> ch1_03
  ch1_03 --> ch1_04
  ch1_04 --> ch1_05
  ch1_05 --> ch1_06
  ch1_06 -- "明天去面试，这是最后的机会了" --> ch1_07
  ch1_06 -- "算了，连十九家都不要我，第二十家也不会要的" --> ch1_06a
  ch1_06a --> ch1_07
  ch1_07 --> ch1_08
  ch1_08 --> ch1_09
  ch1_09 --> ch1_10
  ch1_10 --> ch1_11
  ch1_11 --> ch1_12
  ch1_12 --> ch1_13
  ch1_13 --> ch1_14
  ch1_14 --> ch1_15
  ch1_15 --> ch1_16
  ch1_16 --> ch1_17
  ch1_17 --> ch1_18
  ch1_18 --> ch1_19
  ch1_19 --> ch1_20
  ch1_20 -- "可是他们确实比我强，我什么都没有" --> ch1_20a
  ch1_20 -- "你说得对，我不应该妄自菲薄" --> ch1_20b
  ch1_20 -- "我只是想先活下去，其他的以后再说" --> ch1_20c
  ch1_20a --> ch1_21
  ch1_20b --> ch1_21
  ch1_20c --> ch1_21
  ch1_21 --> ch1_22
  ch1_22 --> ch1_23
  ch1_23 --> ch1_24
  ch1_24 --> ch1_25
